### ISSUE TITLE
Doesn't work with the ESP32-ADF

### ISSUE THREAD

**Issue by jwktje** [OLIMEX/MOD-LCD2.8RTP#5]
The example doesn't run on the ESP32-ADF. Which pins do I use? 

I'm using the ESP32-ADF RevC

I'm also not sure what board to select when flashing. The ESP32-ADF isn't shown in the list of boards to choose from.

**Comment by DanKoloff** [comment]
There are demos for ESP32-ADF and MOD-LCD2.8RTP for ESP-IDF, you can find them at ESP32's product page. Exploring these demos might give you ideas on how to get it working under Arduino IDE.

> The example doesn't run on the ESP32-ADF.

Well, ESP32-ADF had no configuration in Board_Pinout.h.

There were configurations for ESP32-POE, ESP32-POE-ISO, ESP32-EVB, OLIMEXINO-2560, OLIMEXINO-STM32F3.

> Which pins do I use?

The pins at the UEXT, trace them in the schematic and add them to Board_Pinout.h, on quick look it seems to be the following pins:

#define TFT_DC 12
#define TFT_CS 15
#define TFT_MOSI 13
#define TFT_CLK 14

> The ESP32-ADF isn't shown in the list of boards to choose from.

You can use "ESP32 Wrover Module" entry, since ESP32-ADF uses ESP32-WROVER. Notice that if you select "ESP32 Wrover Module", then the block to add in Board_Pinout.h would be:

#elif defined ARDUINO_ESP32_DEV
//This is if you select ESP32 Wrover Module
    #define TFT_DC 12
    #define TFT_CS 15
    #define TFT_MOSI 13
    #define TFT_CLK 14
    #define TFT_MISO -1
    #define TFT_RST -1

You would also need to change the pins for the I2C, either in the variant definitions or better in the code directly with Wire.begin(18,23);

To save you some time I also did it and updated the example on the GitHub, download all files and try it yourself.
